FROM python:3.12

WORKDIR /app

COPY . .

EXPOSE 8002

RUN pip install --no-cache-dir --upgrade pip && \
    xargs -n 1 pip install --no-deps < requirements.lightweight.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]